# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Truck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
