# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Truck', '0002_product_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('demand_breakfast', models.IntegerField(default=0)),
                ('demand_meal', models.IntegerField(default=0)),
                ('demand_drink', models.IntegerField(default=0)),
                ('demand_snack', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='truck',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
