# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Truck', '0003_auto_20180724_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='demand_breakfast',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='demand_drink',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='demand_meal',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='demand_snack',
            field=models.IntegerField(default=50),
        ),
    ]
