# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Truck', '0003_auto_20180723_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='Ingredient_name',
            new_name='ingredient_name',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Ingredient_type',
            new_name='ingredient_type',
        ),
    ]
