# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Truck', '0006_auto_20180723_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fund',
            field=models.FloatField(default=1000),
        ),
    ]
