# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Truck', '0007_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Food_Truck.User'),
        ),
    ]
