# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Truck', '0008_report_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='perishable',
            field=models.BooleanField(default=False),
        ),
    ]
