# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Truck', '0009_ingredient_perishable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrade',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='Food_Truck.User'),
        ),
    ]
