# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Truck', '0010_auto_20180725_1612'),
        ('Food_Truck', '0010_auto_20180725_1549'),
    ]

    operations = [
    ]
