# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Truck', '0012_upgrade_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
