# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Truck', '0013_ingredient_level'),
        ('Food_Truck', '0011_merge_20180725_2352'),
    ]

    operations = [
    ]
