# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Truck', '0015_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_log',
            field=models.DateTimeField(null=True),
        ),
    ]
