# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Truck', '0016_user_last_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot1', to='Food_Truck.Product')),
                ('slot_2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot2', to='Food_Truck.Product')),
                ('slot_3', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot3', to='Food_Truck.Product')),
                ('slot_4', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot4', to='Food_Truck.Product')),
                ('slot_5', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot5', to='Food_Truck.Product')),
                ('slot_6', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot6', to='Food_Truck.Product')),
                ('slot_7', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot7', to='Food_Truck.Product')),
                ('slot_8', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot8', to='Food_Truck.Product')),
                ('truck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Food_Truck.Truck')),
            ],
        ),
    ]
