# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Truck', '0017_sales_slot'),
        ('Food_Truck', '0011_merge_20180726_0106'),
    ]

    operations = [
    ]
