# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-27 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Truck', '0018_merge_20180726_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_slot',
            name='slot_1',
        ),
        migrations.RemoveField(
            model_name='sales_slot',
            name='slot_2',
        ),
        migrations.RemoveField(
            model_name='sales_slot',
            name='slot_3',
        ),
        migrations.RemoveField(
            model_name='sales_slot',
            name='slot_4',
        ),
        migrations.RemoveField(
            model_name='sales_slot',
            name='slot_5',
        ),
        migrations.RemoveField(
            model_name='sales_slot',
            name='slot_6',
        ),
        migrations.RemoveField(
            model_name='sales_slot',
            name='slot_7',
        ),
        migrations.RemoveField(
            model_name='sales_slot',
            name='slot_8',
        ),
        migrations.RemoveField(
            model_name='sales_slot',
            name='truck',
        ),
        migrations.DeleteModel(
            name='Sales_Slot',
        ),
    ]
