# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-27 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Truck', '0019_auto_20180726_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='cost',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
