# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Truck', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='buy_price',
        ),
        migrations.AddField(
            model_name='product',
            name='sell_price',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
