# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Truck', '0007_auto_20180723_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredient_A',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_a', to='Food_Truck.Ingredient'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient_B',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_b', to='Food_Truck.Ingredient'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient_C',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_c', to='Food_Truck.Ingredient'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient_D',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_d', to='Food_Truck.Ingredient'),
        ),
    ]
