# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255)),
                ('ingredient_type', models.CharField(max_length=255)),
                ('buy_price', models.FloatField()),
                ('stock', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('sell_price', models.FloatField()),
                ('stock', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient_A', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_a', to='Food_Truck.Ingredient')),
                ('ingredient_B', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_b', to='Food_Truck.Ingredient')),
                ('ingredient_C', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_c', to='Food_Truck.Ingredient')),
                ('ingredient_D', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_d', to='Food_Truck.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.FloatField(default=1000)),
                ('has_truck', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='truck',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='Food_Truck.User'),
        ),
    ]
